// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>

void on_pwm_duty_update(lv_event_t * e)
{
	// 打印arc的pwm占空比
	lv_obj_t * obj = lv_event_get_target(e);
	uint16_t duty = lv_arc_get_value(obj);
	printf("PWM duty: %d\n", duty);

}
